export interface Product {
    title: string;
    type: string;
    description: string;
    filename: string;
    height: number;
    width: number;
    price: number;
    rating: number;
}

export interface Images{
    '0.jpg': string
    '1.jpg': string
    '2.jpg': string
    '3.jpg': string
    '4.jpg': string
    '5.jpg': string
    '6.jpg': string
    '7.jpg': string
    '8.jpg': string
    '9.jpg': string
    '10.jpg': string
    '11.jpg': string
    '12.jpg': string
    '13.jpg': string
    '14.jpg': string
    '15.jpg': string
    '16.jpg': string
    '17.jpg': string
    '18.jpg': string
    '19.jpg': string
    '20.jpg': string
    '21.jpg': string
    '22.jpg': string
    '23.jpg': string
    '24.jpg': string
    '25.jpg': string
    '26.jpg': string
    '27.jpg': string
    '28.jpg': string
    '29.jpg': string
    '30.jpg': string
    '31.jpg': string
    '32.jpg': string
    '33.jpg': string
    '34.jpg': string
    '35.jpg': string
    '36.jpg': string
    '37.jpg': string
    '38.jpg': string
    '39.jpg': string
    '40.jpg': string
    '41.jpg': string
    '42.jpg': string
    '43.jpg': string
    '44.jpg': string
    '45.jpg': string
    '46.jpg': string
    '47.jpg': string
    '48.jpg': string
    '49.jpg': string
    '50.jpg': string
}